"""Pop Quiz Answers"""

question_data = [
    {
        "category": "Science & Nature",
        "type": "boolean",
        "difficulty": "medium",
        "question": "The Neanderthals were a direct ancestor of modern humans.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "category": "Animals",
        "type": "boolean",
        "difficulty": "medium",
        "question": "The Ceratosaurus, a dinosaur known for having a horn on the top of its nose, is also known to be a"
        " descendent of the Tyrannosaurus Rex.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "category": "Science: Mathematics",
        "type": "boolean",
        "difficulty": "medium",
        "question": "The Pythagorean theorem states that the square of the hypotenuse is equal to the product of the "
        "squares of the other two sides.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "category": "Entertainment: Music",
        "type": "boolean",
        "difficulty": "medium",
        "question": "Soulja Boy's 'Crank That'; won a Grammy for Best Rap Song in 2007.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "category": "Geography",
        "type": "boolean",
        "difficulty": "medium",
        "question": "The surface area of Russia is slightly larger than that of the dwarf planet Pluto.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "category": "Science & Nature",
        "type": "boolean",
        "difficulty": "medium",
        "question": "The Gympie Stinger is the deadliest plant in the world.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "category": "Science: Computers",
        "type": "boolean",
        "difficulty": "medium",
        "question": "All program codes have to be compiled into an executable file in order to be run. This file "
        "can then be executed on any machine.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "category": "Science & Nature",
        "type": "boolean",
        "difficulty": "medium",
        "question": "Steel is an alloy of Iron and Carbon.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "category": "General Knowledge",
        "type": "boolean",
        "difficulty": "medium",
        "question": "The vapour produced by e-cigarettes is actually water.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "category": "Entertainment: Music",
        "type": "boolean",
        "difficulty": "medium",
        "question": "Scottish producer Calvin Harris is from the town of Dumfries, Scotland.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "category": "Animals",
        "type": "boolean",
        "difficulty": "medium",
        "question": "'Kamea,' the Gilbertese Islander word for dog, is " "derived from the English phrase 'Come here!'",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "category": "Geography",
        "type": "boolean",
        "difficulty": "medium",
        "question": "The longest place named in the United States is Lake "
        "Chargoggagoggmanchauggagoggchaubunagungamaugg, located near Webster, MA.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "category": "Entertainment: Video Games",
        "type": "boolean",
        "difficulty": "medium",
        "question": "'Metal Gear Solid 3: Snake Eater' takes place on Shadow Moses Island.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "category": "General Knowledge",
        "type": "boolean",
        "difficulty": "medium",
        "question": "An eggplant is a vegetable.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "category": "Entertainment: Video Games",
        "type": "boolean",
        "difficulty": "medium",
        "question": "Metal Gear Solid V: The Phantom Pain runs on the Fox Engine.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "category": "General Knowledge",
        "type": "boolean",
        "difficulty": "medium",
        "question": "Cucumbers are usually more than 90% water.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "category": "Science & Nature",
        "type": "boolean",
        "difficulty": "medium",
        "question": "Scientists accidentally killed the once known world's oldest "
        "living creature, a mollusc, known to be aged as 507 years old.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "category": "History",
        "type": "boolean",
        "difficulty": "medium",
        "question": "Theodore Roosevelt Jr. was the only General involved in the initial assault on D-Day.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "category": "Vehicles",
        "type": "boolean",
        "difficulty": "medium",
        "question": "When BMW was established in 1916, it was producing automotives.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "category": "Entertainment: Video Games",
        "type": "boolean",
        "difficulty": "medium",
        "question": "The Sniper's SMG in Team Fortress 2, was originally intended to be the " "Scout's primary weapon.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "category": "Sports",
        "type": "boolean",
        "difficulty": "medium",
        "question": "The Olympics tennis court is a giant green screen.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "category": "Animals",
        "type": "boolean",
        "difficulty": "medium",
        "question": "The Platypus is a mammal.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "category": "Vehicles",
        "type": "boolean",
        "difficulty": "medium",
        "question": "Arriva is owned by the Deutsche Bahn.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "category": "Geography",
        "type": "boolean",
        "difficulty": "medium",
        "question": "Liechtenstein does not have an airport.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "category": "Science: Computers",
        "type": "boolean",
        "difficulty": "medium",
        "question": "The first dual-core CPU was the Intel Pentium D.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "category": "Sports",
        "type": "boolean",
        "difficulty": "medium",
        "question": "Formula E is an auto racing series that uses hybrid electric race cars.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "category": "Entertainment: Cartoon & Animations",
        "type": "boolean",
        "difficulty": "medium",
        "question": "Nickelodeon rejected the pilot to Adventure Time.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "category": "Entertainment: Music",
        "type": "boolean",
        "difficulty": "medium",
        "question": "Pink Guy's debut album was 'Pink Season'.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "category": "Entertainment: Television",
        "type": "boolean",
        "difficulty": "medium",
        "question": "Klingons once had a period of Democracy in their history, they referred to "
        "it as the 'Dark Times'.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "category": "Science: Mathematics",
        "type": "boolean",
        "difficulty": "medium",
        "question": "The set of all algebraic numbers is countable.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "category": "Entertainment: Music",
        "type": "boolean",
        "difficulty": "medium",
        "question": "Nick Mason is the only member to appear on every Pink Floyd album.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "category": "General Knowledge",
        "type": "boolean",
        "difficulty": "medium",
        "question": "Haggis is traditionally ate on Burns Night.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "category": "Entertainment: Music",
        "type": "boolean",
        "difficulty": "medium",
        "question": "Musical artist, Future, collaborated with Kendrick Lamar for the song: 'Mask Off'.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "category": "Entertainment: Music",
        "type": "boolean",
        "difficulty": "medium",
        "question": "Dave Grohl recorded the Foo Fighters' debut, 'Foo Fighters,' by himself.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "category": "History",
        "type": "boolean",
        "difficulty": "medium",
        "question": "The Korean War ended in 1953 without any ceasefire.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "category": "History",
        "type": "boolean",
        "difficulty": "medium",
        "question": "Sir Isaac Newton served as a Member of Parliament, but the only recorded time he spoke was "
        "to complain about a draft in the chambers.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "category": "General Knowledge",
        "type": "boolean",
        "difficulty": "medium",
        "question": "Popcorn was invented in 1871 by Frederick W. Ruckriem in the USA where he sold the "
        "snack on the streets of Chicago.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "category": "Sports",
        "type": "boolean",
        "difficulty": "medium",
        "question": "In 2008, Usain Bolt set the world record for the 100 meters with one shoelace untied.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "category": "Sports",
        "type": "boolean",
        "difficulty": "medium",
        "question": "ATP tennis hosted several tournaments on carpet court before being replaced to reduce injuries.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "category": "Entertainment: Books",
        "type": "boolean",
        "difficulty": "medium",
        "question": "Originally, the character Charlie from Charlie and the Chocolate Factory was going to be black.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "category": "Entertainment: Video Games",
        "type": "boolean",
        "difficulty": "medium",
        "question": "In the Resident Evil series, Leon S. Kennedy is a member of STARS.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
]
